services:
  web:
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - ./pyproject.toml:/app/pyproject.toml
      - ./tests:/app/tests
      - ./logs:/app/logs

  huey:
    command: python -m watchdog.watchmedo auto-restart --directory=/app --pattern='*.py' --recursive -- python manage.py run_huey
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./manage.py:/app/manage.py
      - ./logs:/app/logs
