services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: obe_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      args:
        DEBUG: ${DEBUG:-false}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media_files:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-compose-development-key
      - DATABASE_URL=postgis://postgres:postgres@db:5432/obe_app
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  huey:
    build:
      context: .
      args:
        DEBUG: ${DEBUG:-false}
    command: python manage.py run_huey
    volumes:
      - media_files:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-compose-development-key
      - DATABASE_URL=postgis://postgres:postgres@db:5432/obe_app
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  media_files:
