# Generated by Django 5.2.5 on 2025-08-15 10:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('area_of_interest', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('source', models.CharField(choices=[('google', 'Google Open Buildings'), ('microsoft', 'Microsoft Building Footprints'), ('osm', 'OpenStreetMap Buildings'), ('overture', 'Overture Buildings')], max_length=20)),
                ('source_config', models.JSONField(blank=True, default=dict)),
                ('output_format', models.CharField(choices=[('geoparquet', 'GeoParquet'), ('geojson', 'GeoJSON'), ('shapefile', 'Shapefile'), ('geopackage', 'GeoPackage')], default='geoparquet', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='exports.export')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['user', '-created_at'], name='exports_exp_user_id_422185_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['is_public', '-created_at'], name='exports_exp_is_publ_175fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrun',
            index=models.Index(fields=['export', '-created_at'], name='exports_exp_export__025df7_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrun',
            index=models.Index(fields=['status', '-created_at'], name='exports_exp_status_5322f4_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrun',
            index=models.Index(fields=['task_id'], name='exports_exp_task_id_c59aad_idx'),
        ),
    ]
