# Generated by Django 5.2.5 on 2025-08-17 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='output_format',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('geoparquet', 'GeoParquet'), ('geojson', 'GeoJSON'), ('shapefile', 'Shapefile'), ('geopackage', 'GeoPackage')], max_length=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='export',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('google', 'Google Open Buildings'), ('microsoft', 'Microsoft Building Footprints'), ('osm', 'OpenStreetMap Buildings'), ('overture', 'Overture Buildings')], max_length=20), size=None),
        ),
    ]
