# Generated by Django 5.2.5 on 2025-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_export_output_format_alter_export_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='tiles_file',
            field=models.FileField(blank=True, null=True, upload_to='tiles/%Y/%m/%d/'),
        ),
    ]
